### ISSUE TITLE
[Business Approvals Kit - Feature]: First Time Approver Notification and Configuration

### ISSUE THREAD

**Issue by miguelverweij** [microsoft/powercat-business-approvals-kit#240]
### Is your feature request related to a problem? Please describe.

It could happen that when a person is selected as an approver, they themselves aren’t aware they are an approver and they might haven’t setup their delegate and/or out of office.

### Describe the solution you'd like

Either when an approver receives an approval first time, or is selected as an approver, they should get some notification they can set it up in approvals kit. 

AB#2525

**Comment by Grant-Archibald-MS** [comment]
@miguelverweij one feature we are adding is an optional ability to check the Microsoft 365 Graph Mailbox settings for OOF. This will make setting OOF easier.

It is a great suggestion to send a notification email to a first time approver so that they are aware they should nominate the delegated approver.

if the delegated approver is not set, we could consider defaulting this to the approvers manager

**Comment by Grant-Archibald-MS** [comment]
Adding link to related configuration for [[Business Approvals Kit - Feature]: Default delegate](https://github.com/microsoft/powercat-business-approvals-kit/issues/239)

**Comment by MCSDWes** [comment]
@Grant-Archibald-MS - I like the auto delegation to the user's manager, with the graph mailbox setting for OOF and the delegation to the approver's manager would mean that approvers would not have to come into the Business Approvals site and set anything up which is how we would want it in our school district.

**Comment by Grant-Archibald-MS** [comment]
@MCSDWes Thanks for the comment. We are working on changes for the next April release now that allow optional configuration so that the out of office settings are queried using the mailbox settings from Microsoft Graph. We are also adding a change that will lookup the approvers manager if they have not setup a Delegate or Backup in the application.

**Comment by Grant-Archibald-MS** [comment]
@MCSDWes the optional Microsoft Graph integration checking the users Mailbox settings and defaulting to manager has been included in the April release of the approvals kt
